"""
Entry signal engines for the IHSG swing trading system.

Three independent engines, each with a consistent interface:
  engine.scan(df, ticker, regime) -> EntrySignal | None

Engine priority (highest to lowest):
  1. FVG Pullback        (priority 3) — pullback into Fair Value Gap
  2. Momentum Breakout   (priority 2) — breakout from tight range
  3. Buying on Weakness   (priority 1) — capitulation reversal
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from config.settings import (
    ATR_PERIOD,
    BOW_BOLLINGER_PERIOD,
    BOW_BOLLINGER_STD,
    BOW_MACD_DIVERGENCE_LOOKBACK,
    BOW_MACD_FAST,
    BOW_MACD_SIGNAL,
    BOW_MACD_SLOW,
    BOW_RSI_THRESHOLD,
    BOW_STOCH_RSI_OVERSOLD,
    BOW_STOCH_RSI_PERIOD,
    BOW_VOLUME_CLIMAX_RATIO,
    BREAKOUT_MAX_SPREAD_PCT,
    BREAKOUT_VOLUME_THRESHOLD,
    FVG_LOW_VOLUME_RATIO,
    REGIME_SMA_SHORT,
    VCLR_CLOSING_RANGE_MAX,
    VCLR_MIN_BODY_PCT,
    VCLR_VOLUME_RATIO,
    WYCKOFF_SPRING_LOOKBACK,
    WYCKOFF_SPRING_VOLUME_RATIO,
)
from core.indicators import (
    atr,
    bollinger_bands,
    closing_range,
    detect_fvg,
    macd,
    rsi,
    sma,
    stoch_rsi,
    volume_ratio,
)
from core.regime import RegimeSnapshot

logger = logging.getLogger(__name__)


# ─── Data Structures ─────────────────────────────────────────────────────────


@dataclass
class EntrySignal:
    """A concrete buy signal generated by an engine."""

    engine: str  # engine name identifier
    ticker: str
    price: float
    score: float  # ranking score (priority * volume_ratio)
    priority: int  # engine priority (3=highest, 1=lowest)
    details: dict = field(default_factory=dict)

    def __str__(self) -> str:
        return (
            f"[{self.engine}] {self.ticker} @ {self.price:,.0f} "
            f"score={self.score:.2f}"
        )


# ─── Base Engine ─────────────────────────────────────────────────────────────


class BaseEngine(ABC):
    """Abstract base for all entry engines."""

    name: str = "base"
    priority: int = 0

    @abstractmethod
    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
    ) -> EntrySignal | None:
        """
        Evaluate a single stock for entry signals.

        Parameters
        ----------
        df : pd.DataFrame
            OHLCV data with DatetimeIndex.
        ticker : str
            Ticker code.
        regime : RegimeSnapshot
            Current market regime state.

        Returns
        -------
        EntrySignal | None
            Signal if triggered, else None.
        """
        ...


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 1: FVG PULLBACK
# ══════════════════════════════════════════════════════════════════════════════


class FVGPullbackEngine(BaseEngine):
    """
    Fair Value Gap Pullback Entry Engine.

    Identifies a 3-candle bullish FVG in an uptrend, then triggers
    a buy when price drops into the FVG zone on low volume and
    prints a higher daily close.

    Conditions:
    1. Stock must be in an uptrend (price > SMA50)
    2. A recent unfilled bullish FVG must exist
    3. Previous day's low penetrated or touched the FVG zone
    4. Volume on the pullback day was below average (< 80%)
    5. Today's close is higher than previous close (reversal)

    Priority: 3 (highest)
    Allowed regimes: BULL, CAUTION
    """

    name = "fvg_pullback"
    priority = 3

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
    ) -> EntrySignal | None:
        # Regime gate
        if not regime.allows_engine(self.name):
            return None

        if len(df) < max(REGIME_SMA_SHORT + 10, 60):
            return None

        last = df.iloc[-1]
        prev = df.iloc[-2]
        last_close = float(last["Close"])
        prev_close = float(prev["Close"])
        prev_low = float(prev["Low"])
        last_open = float(last["Open"])

        # 1. Uptrend check: price above SMA(50)
        sma50 = sma(df["Close"], REGIME_SMA_SHORT)
        if pd.isna(sma50.iloc[-1]) or last_close <= float(sma50.iloc[-1]):
            return None

        # 2. Find recent unfilled bullish FVGs (last 90 calendar days)
        fvgs = detect_fvg(df)
        recent_bullish = [
            g for g in fvgs
            if g.gap_type == "bullish"
            and not g.filled
            and (df.index[-1] - g.date).days <= 90
        ]

        if not recent_bullish:
            return None

        # 3. Volume must be below average on the pullback (previous day)
        vol_ratio = volume_ratio(df, period=20)
        prev_vol_ratio = float(vol_ratio.iloc[-2]) if not pd.isna(vol_ratio.iloc[-2]) else 1.0

        # 4. Check each FVG for a pullback entry
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        for gap in recent_bullish:
            # Previous day's low penetrated or touched the FVG zone
            if prev_low <= gap.gap_high:
                # Low volume on pullback day
                if prev_vol_ratio < FVG_LOW_VOLUME_RATIO:
                    # Today's close is higher (reversal confirmation)
                    if last_close > prev_close and last_close > last_open:
                        last_vol_ratio = float(vol_ratio.iloc[-1]) if not pd.isna(vol_ratio.iloc[-1]) else 1.0
                        score = self.priority * max(last_vol_ratio, 1.0)

                        return EntrySignal(
                            engine=self.name,
                            ticker=ticker,
                            price=round(last_close, 2),
                            score=round(score, 2),
                            priority=self.priority,
                            details={
                                "fvg_date": gap.date.strftime("%Y-%m-%d"),
                                "gap_high": round(gap.gap_high, 2),
                                "gap_low": round(gap.gap_low, 2),
                                "gap_size": round(gap.gap_size, 2),
                                "pullback_vol_ratio": round(prev_vol_ratio, 2),
                                "reversal_vol_ratio": round(last_vol_ratio, 2),
                                "atr": round(last_atr, 2),
                                "sma50": round(float(sma50.iloc[-1]), 2),
                            },
                        )

        return None


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 2: MOMENTUM BREAKOUT
# ══════════════════════════════════════════════════════════════════════════════


class MomentumBreakoutEngine(BaseEngine):
    """
    Momentum Breakout Entry Engine.

    Identifies tight consolidation (max 5% price spread over 20 days),
    then triggers a buy on a daily close above the 20-day high with
    >150% average volume.

    Conditions:
    1. 20-day price range (High-Low spread) must be <= 5% of price
    2. Today's close must be above the 20-day high
    3. Today's volume must be > 150% of 20-day average volume

    Priority: 2
    Allowed regimes: BULL only
    """

    name = "momentum_breakout"
    priority = 2

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
    ) -> EntrySignal | None:
        # Regime gate
        if not regime.allows_engine(self.name):
            return None

        if len(df) < BREAKOUT_CONSOLIDATION_DAYS + 5:
            return None

        last = df.iloc[-1]
        last_close = float(last["Close"])

        # Get the 20-day window BEFORE today
        lookback = df.iloc[-(BREAKOUT_CONSOLIDATION_DAYS + 1):-1]

        if len(lookback) < BREAKOUT_CONSOLIDATION_DAYS:
            return None

        # 1. Tight consolidation: max spread <= 5% of price
        highest = lookback["High"].max()
        lowest = lookback["Low"].min()
        spread_pct = ((highest - lowest) / last_close) * 100.0

        if spread_pct > BREAKOUT_MAX_SPREAD_PCT:
            return None

        # 2. Close above 20-day high
        high_20d = float(lookback["High"].max())
        if last_close <= high_20d:
            return None

        # 3. Volume > 150% average
        vol_ratio_series = volume_ratio(df, period=20)
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        if last_vol_ratio < BREAKOUT_VOLUME_THRESHOLD:
            return None

        # Signal confirmed
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        score = self.priority * last_vol_ratio

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details={
                "consolidation_days": BREAKOUT_CONSOLIDATION_DAYS,
                "spread_pct": round(spread_pct, 2),
                "high_20d": round(high_20d, 2),
                "breakout_pct": round(((last_close - high_20d) / high_20d) * 100, 2),
                "volume_ratio": round(last_vol_ratio, 2),
                "atr": round(last_atr, 2),
            },
        )


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 3: BUYING ON WEAKNESS (B.O.W.)
# ══════════════════════════════════════════════════════════════════════════════


class BuyingOnWeaknessEngine(BaseEngine):
    """
    Buying on Weakness (B.O.W.) Entry Engine.

    Identifies extreme capitulation and triggers a buy on a
    bullish reversal candle with massive volume.

    Capitulation conditions (one or both):
    - Price < Lower Bollinger Band (20-period, 2 std)
    - RSI(14) < 25

    Entry trigger:
    - Volume climax: today's volume > 200% of 20-day average
    - Bullish reversal candle: close > open (green candle)
    - Close > previous close (higher daily close)

    Priority: 1 (lowest)
    Allowed regimes: ALL (designed for crashes)
    """

    name = "buying_on_weakness"
    priority = 1

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
    ) -> EntrySignal | None:
        # B.O.W. fires in any regime — no gate check
        if not regime.allows_engine(self.name):
            return None

        if len(df) < max(BOW_BOLLINGER_PERIOD + 5, 30):
            return None

        last = df.iloc[-1]
        prev = df.iloc[-2]
        last_close = float(last["Close"])
        last_open = float(last["Open"])
        prev_close = float(prev["Close"])

        # ── Capitulation Check ────────────────────────────────────────
        rsi_series = rsi(df["Close"], period=14)
        prev_rsi = float(rsi_series.iloc[-2]) if not pd.isna(rsi_series.iloc[-2]) else 50.0

        upper_bb, middle_bb, lower_bb = bollinger_bands(
            df["Close"], period=BOW_BOLLINGER_PERIOD, num_std=BOW_BOLLINGER_STD
        )
        prev_lower_bb = float(lower_bb.iloc[-2]) if not pd.isna(lower_bb.iloc[-2]) else 0.0

        # Condition 1: Extreme RSI
        capitulation_rsi = prev_rsi < BOW_RSI_THRESHOLD
        
        # Condition 2: Bollinger Band Capitulation
        capitulation_bb = prev_close < prev_lower_bb

        # Condition 3: StochRSI Oversold Bounce
        stoch_k, stoch_d = stoch_rsi(df["Close"], period=BOW_STOCH_RSI_PERIOD)
        prev_k = float(stoch_k.iloc[-2]) if not pd.isna(stoch_k.iloc[-2]) else 50.0
        prev_d = float(stoch_d.iloc[-2]) if not pd.isna(stoch_d.iloc[-2]) else 50.0
        last_k = float(stoch_k.iloc[-1]) if not pd.isna(stoch_k.iloc[-1]) else 50.0
        last_d = float(stoch_d.iloc[-1]) if not pd.isna(stoch_d.iloc[-1]) else 50.0
        
        capitulation_stoch = (
            prev_k < BOW_STOCH_RSI_OVERSOLD and 
            prev_d < BOW_STOCH_RSI_OVERSOLD and 
            last_k > last_d and  # Bullish cross today
            prev_k <= prev_d     # Was below or equal yesterday
        )

        # Condition 4: MACD Bullish Divergence
        macd_line, signal_line, macd_hist = macd(
            df["Close"], fast=BOW_MACD_FAST, slow=BOW_MACD_SLOW, signal=BOW_MACD_SIGNAL
        )
        
        capitulation_macd = False
        if len(df) > BOW_MACD_DIVERGENCE_LOOKBACK + 5:
            # Lookback window for price and MACD histogram
            lookback_lows = df["Low"].iloc[-(BOW_MACD_DIVERGENCE_LOOKBACK+1):-1]
            lookback_hists = macd_hist.iloc[-(BOW_MACD_DIVERGENCE_LOOKBACK+1):-1]
            
            min_low_idx = lookback_lows.idxmin()
            min_low_val = lookback_lows.min()
            
            # If price made a lower low recently compared to the N-day window
            if prev["Low"] <= min_low_val:
                # Find the histogram value at that previous absolute low
                hist_at_min_low = macd_hist.loc[min_low_idx]
                prev_hist = macd_hist.iloc[-2]
                
                # Divergence: Price is lower/equal, but Histogram is higher (less negative)
                if prev_hist < 0 and prev_hist > hist_at_min_low:
                    capitulation_macd = True

        if not (capitulation_rsi or capitulation_bb or capitulation_stoch or capitulation_macd):
            return None

        # ── Entry Trigger ─────────────────────────────────────────────
        # Volume climax today
        vol_ratio_series = volume_ratio(df, period=20)
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        if last_vol_ratio < BOW_VOLUME_CLIMAX_RATIO:
            return None

        # Bullish reversal candle: close > open AND close > prev close
        if not (last_close > last_open and last_close > prev_close):
            return None

        # Signal confirmed
        last_rsi = float(rsi_series.iloc[-1]) if not pd.isna(rsi_series.iloc[-1]) else 50.0
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        # Score B.O.W. signals by volume intensity
        score = self.priority * last_vol_ratio

        capitulation_reason = []
        if capitulation_rsi:
            capitulation_reason.append(f"RSI={prev_rsi:.1f}<{BOW_RSI_THRESHOLD}")
        if capitulation_bb:
            capitulation_reason.append(f"below_lower_BB={prev_lower_bb:.0f}")
        if capitulation_stoch:
            capitulation_reason.append("StochRSI_Cross")
        if capitulation_macd:
            capitulation_reason.append("MACD_Div")

        details = {
            "capitulation": " + ".join(capitulation_reason),
            "prev_rsi": round(prev_rsi, 2),
            "current_rsi": round(last_rsi, 2),
            "volume_ratio": round(last_vol_ratio, 2),
            "prev_close": round(prev_close, 2),
            "lower_bb": round(prev_lower_bb, 2),
            "atr": round(last_atr, 2),
        }
        
        if capitulation_stoch:
            details["stoch_k"] = round(last_k, 2)
            details["stoch_d"] = round(last_d, 2)
            
        if capitulation_macd:
            details["macd_hist"] = round(float(macd_hist.iloc[-1]), 4)

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details=details,
        )


# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 4: WYCKOFF PHASE C SPRING
# ══════════════════════════════════════════════════════════════════════════════


class WyckoffSpringEngine(BaseEngine):
    """
    Wyckoff Phase C Spring Entry Engine.

    Identifies a false breakdown (spring) below a 60-day trading range low.
    Triggers a buy ONLY when the daily low sweeps strictly below the 60-day minimum,
    but the daily close recovers above that minimum line on climax volume.

    Priority: 1
    Allowed regimes: CAUTION (Mean-Reverting)
    """

    name = "wyckoff_spring"
    priority = 1

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
    ) -> EntrySignal | None:
        if not regime.allows_engine(self.name):
            return None

        if len(df) < WYCKOFF_SPRING_LOOKBACK + 5:
            return None

        last = df.iloc[-1]
        last_low = float(last["Low"])
        last_close = float(last["Close"])

        # Lookback window BEFORE today
        lookback = df.iloc[-(WYCKOFF_SPRING_LOOKBACK + 1):-1]
        
        if len(lookback) < WYCKOFF_SPRING_LOOKBACK:
            return None

        min_60d = float(lookback["Low"].min())

        # 1. Sweep strictly below 60-day minimum
        if last_low >= min_60d:
            return None

        # 2. Close recovers above 60-day minimum
        if last_close <= min_60d:
            return None

        # 3. Climax volume (> 200% average)
        vol_ratio_series = volume_ratio(df, period=20)
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        if last_vol_ratio < WYCKOFF_SPRING_VOLUME_RATIO:
            return None

        # Signal confirmed
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0

        score = self.priority * last_vol_ratio

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details={
                "lookback_days": WYCKOFF_SPRING_LOOKBACK,
                "range_low": round(min_60d, 2),
                "sweep_low": round(last_low, 2),
                "sweep_depth_pct": round(((min_60d - last_low) / min_60d) * 100, 2),
                "volume_ratio": round(last_vol_ratio, 2),
                "atr": round(last_atr, 2),
            },
        )



# ══════════════════════════════════════════════════════════════════════════════
# ENGINE 5: VOLUME CLIMAX REVERSAL
# ══════════════════════════════════════════════════════════════════════════════


class VolumeClimaxReversalEngine(BaseEngine):
    """
    Volume Climax Reversal Entry Engine.

    Identifies extreme volume exhaustion events where a massive volume spike
    (>300% of 20-day average) occurs with a bearish wide-range candle
    (Closing Range < 0.25), suggesting selling climax exhaustion.

    The entry triggers when today's price action confirms demand absorption:
    close > previous close AND close > open (bullish candle).

    Conditions:
    1. Previous day: Volume > 300% of 20-day average (climax volume)
    2. Previous day: Closing Range < 0.25 (closed near the low)
    3. Previous day: Body size > 1.5% of price (real move, not a doji)
    4. Today: Close > Previous Close AND Close > Open (bullish reversal)

    Priority: 2
    Allowed regimes: BULL, CAUTION
    """

    name = "volume_climax_reversal"
    priority = 2

    def scan(
        self,
        df: pd.DataFrame,
        ticker: str,
        regime: RegimeSnapshot,
    ) -> EntrySignal | None:
        if not regime.allows_engine(self.name):
            return None

        if len(df) < 25:
            return None

        last = df.iloc[-1]
        prev = df.iloc[-2]
        last_close = float(last["Close"])
        last_open = float(last["Open"])
        prev_close = float(prev["Close"])
        prev_open = float(prev["Open"])
        prev_high = float(prev["High"])
        prev_low = float(prev["Low"])

        # 1. Previous day volume climax (> 300% of 20-day average)
        vol_ratio_series = volume_ratio(df, period=20)
        prev_vol_ratio = float(vol_ratio_series.iloc[-2]) if not pd.isna(vol_ratio_series.iloc[-2]) else 1.0

        if prev_vol_ratio < VCLR_VOLUME_RATIO:
            return None

        # 2. Previous day closing range < 0.25 (closed near the low = bearish exhaustion)
        cr_series = closing_range(df)
        prev_cr = float(cr_series.iloc[-2]) if not pd.isna(cr_series.iloc[-2]) else 0.5

        if prev_cr >= VCLR_CLOSING_RANGE_MAX:
            return None

        # 3. Previous day body size > 1.5% (real move, not a doji)
        body_pct = abs(prev_close - prev_open) / prev_close * 100.0
        if body_pct < VCLR_MIN_BODY_PCT:
            return None

        # 4. Today's reversal confirmation: close > prev_close AND close > open
        if not (last_close > prev_close and last_close > last_open):
            return None

        # Signal confirmed
        atr_series = atr(df, period=ATR_PERIOD)
        last_atr = float(atr_series.iloc[-1]) if not pd.isna(atr_series.iloc[-1]) else 0.0
        last_vol_ratio = float(vol_ratio_series.iloc[-1]) if not pd.isna(vol_ratio_series.iloc[-1]) else 1.0

        score = self.priority * prev_vol_ratio

        return EntrySignal(
            engine=self.name,
            ticker=ticker,
            price=round(last_close, 2),
            score=round(score, 2),
            priority=self.priority,
            details={
                "climax_vol_ratio": round(prev_vol_ratio, 2),
                "climax_closing_range": round(prev_cr, 2),
                "climax_body_pct": round(body_pct, 2),
                "reversal_vol_ratio": round(last_vol_ratio, 2),
                "atr": round(last_atr, 2),
            },
        )


# ─── Engine Registry ─────────────────────────────────────────────────────────

# Ordered by priority (highest first) — this is the evaluation order
ALL_ENGINES: list[BaseEngine] = [
    FVGPullbackEngine(),
    MomentumBreakoutEngine(),
    BuyingOnWeaknessEngine(),
    WyckoffSpringEngine(),
    VolumeClimaxReversalEngine(),
]


def run_all_engines(
    df: pd.DataFrame,
    ticker: str,
    regime: RegimeSnapshot,
) -> list[EntrySignal]:
    """
    Run all engines against a single stock and collect signals.

    Returns a list of all signals that fired (usually 0 or 1).
    Multiple engines can fire on the same stock.
    """
    signals: list[EntrySignal] = []
    for engine in ALL_ENGINES:
        try:
            signal = engine.scan(df, ticker, regime)
            if signal:
                signals.append(signal)
                logger.debug(
                    "[%s] Engine '%s' fired: %s",
                    ticker, engine.name, signal,
                )
        except Exception as e:
            logger.warning(
                "[%s] Engine '%s' error: %s", ticker, engine.name, e
            )
    return signals
